package panel;

import panel.pndata;
import java.awt.event.ActionListener;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.Icon;

public class menuItem extends javax.swing.JPanel {
    
    private ActionListener hearTofunction;
    
    pndata abc = new pndata();
    
    private ArrayList<menuItem> subMenu = new ArrayList<>();
    
    public ArrayList<menuItem> getSubMenu() {
        return subMenu;
    }
    
    private void sleep(){
        try{
            Thread.sleep(25);
        }catch(Exception e){
        }
    }
    
    private void hideMenu(){
        new Thread(new Runnable(){
            @Override
            public void run(){
                for(int i=subMenu.size()-1; i>=0;i--){
                    sleep();
                    subMenu.get(i).setVisible(false);
                    subMenu.get(i).hideMenu();
                }
                getParent().repaint();
                getParent().revalidate();
                showing=false;
            }
        }).start();
        
    }
    private void showMenu(){
        new Thread(new Runnable(){
            @Override
            public void run(){
                for(int i=0;i<subMenu.size();i++){
                    sleep();
                    subMenu.get(i).setVisible(true);
                }
                showing=true;
                getParent().repaint();
                getParent().revalidate();
            }
        }).start();
    }
    public menuItem(Icon icon, boolean sbm, Icon subIcon, String menuName, ActionListener hearTofunction, menuItem...subMenu) {
        initComponents();
        
        lb_icon.setIcon(icon);
        lb_txtMenu.setText(menuName);
        lb_subIcon.setIcon(subIcon);
        lb_subIcon.setVisible(sbm);
        
        if (hearTofunction !=null){
            this.hearTofunction = hearTofunction;
        }
        
        this.setSize(new Dimension(Integer.MAX_VALUE, 60));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 60));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 50));
        for(int i=0; i<subMenu.length; i++){
           this.subMenu.add(subMenu[i]);
        }
        setBackground(new java.awt.Color(255,255,255));
    }
    private boolean showing;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_icon = new javax.swing.JLabel();
        lb_subIcon = new javax.swing.JLabel();
        lb_txtMenu = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        lb_txtMenu.setText("Menu Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_subIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_txtMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_subIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_txtMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        setBackground(new java.awt.Color(220,220,220));
        if(showing){
            hideMenu();
        }else{
            showMenu();
        }
        if(hearTofunction !=null){
            hearTofunction.actionPerformed(null);
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(new java.awt.Color(245,245,245));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_formMouseExited

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        setBackground(new java.awt.Color(245,245,245));
    }//GEN-LAST:event_formMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_subIcon;
    private javax.swing.JLabel lb_txtMenu;
    // End of variables declaration//GEN-END:variables
}
