package panel;

import reports.viewUI;
import config.rdbreports;
import config.rootdb;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;

public class pnreport extends javax.swing.JPanel implements viewUI{
    
    private rdbreports koneksi = new rdbreports();
    private rootdb con = new rootdb();
    private ResultSet rs;
    private int slcV;
    
    public int getSlcV() {
        return slcV;
    }

    @Override
    public void engineV(){
        if(getSlcV()==1){
            mnl_content.removeAll();
            mnl_content.add(D);
            mnl_content.repaint();
            mnl_content.revalidate();
            cbxD.addItem("=====PILIH ITEM=====");
            try{
                rs=con.adapter.executeQuery("SELECT DISTINCT tgltrs FROM nota");
                while(rs.next()){
                    cbxD.addItem(rs.getString("tgltrs"));
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"GAGAL MENAMPILKAN TANGGAL !!!","WARNING",JOptionPane.WARNING_MESSAGE);
            }
        }else if(getSlcV()==2){
            mnl_content.removeAll();
            mnl_content.add(M);
            mnl_content.repaint();
            mnl_content.revalidate();
            cbxM.addItem("=====PILIH ITEM=====");
            try{
                rs=con.adapter.executeQuery("SELECT DISTINCT tgltrs FROM nota");
                while(rs.next()){
                    cbxM.addItem(rs.getString("tgltrs").substring(3));
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"GAGAL MENAMPILKAN BULAN !!!","WARNING",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            mnl_content.removeAll();
            mnl_content.add(Y);
            mnl_content.repaint();
            mnl_content.revalidate();
            cbxY.addItem("=====PILIH ITEM=====");
            try{
                rs=con.adapter.executeQuery("SELECT DISTINCT tgltrs FROM nota");
                while(rs.next()){
                    cbxY.addItem(rs.getString("tgltrs").substring(6));
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"GAGAL MENAMPILKAN TAHUN !!!","WARNING",JOptionPane.WARNING_MESSAGE);
            }

        }
    }
    public pnreport(int slcV) {
        con.root();
        initComponents();
        this.slcV = slcV;
        engineV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnl_content = new javax.swing.JPanel();
        D = new javax.swing.JPanel();
        HeaderD = new javax.swing.JPanel();
        lbjdlD = new javax.swing.JLabel();
        lbvarD = new javax.swing.JLabel();
        cbxD = new javax.swing.JComboBox<>();
        btnD = new javax.swing.JButton();
        BodyD = new javax.swing.JPanel();
        M = new javax.swing.JPanel();
        HeaderM = new javax.swing.JPanel();
        lbjdlM = new javax.swing.JLabel();
        lbvarM = new javax.swing.JLabel();
        cbxM = new javax.swing.JComboBox<>();
        btnM = new javax.swing.JButton();
        BodyM = new javax.swing.JPanel();
        Y = new javax.swing.JPanel();
        HeaderY = new javax.swing.JPanel();
        lbjdlY = new javax.swing.JLabel();
        lbvarY = new javax.swing.JLabel();
        cbxY = new javax.swing.JComboBox<>();
        btnY = new javax.swing.JButton();
        BodyY = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        mnl_content.setLayout(new java.awt.CardLayout());

        HeaderD.setBackground(new java.awt.Color(5, 206, 5));
        HeaderD.setPreferredSize(new java.awt.Dimension(800, 60));

        lbjdlD.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        lbjdlD.setText("HARIAN VIEWS");

        lbvarD.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbvarD.setText("Tanggal");

        cbxD.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        btnD.setBackground(new java.awt.Color(255, 154, 73));
        btnD.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnD.setForeground(new java.awt.Color(255, 255, 255));
        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnD.setText("CARI");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderDLayout = new javax.swing.GroupLayout(HeaderD);
        HeaderD.setLayout(HeaderDLayout);
        HeaderDLayout.setHorizontalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbjdlD, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(lbvarD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderDLayout.setVerticalGroup(
            HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderDLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(HeaderDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbvarD)
                    .addComponent(lbjdlD))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        BodyD.setBackground(new java.awt.Color(224, 222, 94));
        BodyD.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout DLayout = new javax.swing.GroupLayout(D);
        D.setLayout(DLayout);
        DLayout.setHorizontalGroup(
            DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BodyD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DLayout.setVerticalGroup(
            DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DLayout.createSequentialGroup()
                .addComponent(HeaderD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BodyD, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
        );

        mnl_content.add(D, "card2");

        HeaderM.setBackground(new java.awt.Color(5, 206, 5));
        HeaderM.setPreferredSize(new java.awt.Dimension(800, 60));

        lbjdlM.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        lbjdlM.setText("BULANAN VIEWS");

        lbvarM.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbvarM.setText("Bulan");

        cbxM.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        btnM.setBackground(new java.awt.Color(255, 154, 73));
        btnM.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnM.setForeground(new java.awt.Color(255, 255, 255));
        btnM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnM.setText("CARI");
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderMLayout = new javax.swing.GroupLayout(HeaderM);
        HeaderM.setLayout(HeaderMLayout);
        HeaderMLayout.setHorizontalGroup(
            HeaderMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbjdlM, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbvarM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderMLayout.setVerticalGroup(
            HeaderMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderMLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(HeaderMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbvarM)
                    .addComponent(lbjdlM))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        BodyM.setBackground(new java.awt.Color(224, 222, 94));
        BodyM.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout MLayout = new javax.swing.GroupLayout(M);
        M.setLayout(MLayout);
        MLayout.setHorizontalGroup(
            MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BodyM, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(HeaderM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MLayout.setVerticalGroup(
            MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MLayout.createSequentialGroup()
                .addComponent(HeaderM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BodyM, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
        );

        mnl_content.add(M, "card2");

        HeaderY.setBackground(new java.awt.Color(5, 206, 5));
        HeaderY.setPreferredSize(new java.awt.Dimension(800, 60));

        lbjdlY.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        lbjdlY.setText("TAHUNAN VIEWS");

        lbvarY.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbvarY.setText("Tahunan");

        cbxY.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        btnY.setBackground(new java.awt.Color(255, 154, 73));
        btnY.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnY.setForeground(new java.awt.Color(255, 255, 255));
        btnY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnY.setText("CARI");
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderYLayout = new javax.swing.GroupLayout(HeaderY);
        HeaderY.setLayout(HeaderYLayout);
        HeaderYLayout.setHorizontalGroup(
            HeaderYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderYLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbjdlY, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbvarY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxY, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderYLayout.setVerticalGroup(
            HeaderYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderYLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(HeaderYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbvarY)
                    .addComponent(lbjdlY))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        BodyY.setBackground(new java.awt.Color(224, 222, 94));
        BodyY.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout YLayout = new javax.swing.GroupLayout(Y);
        Y.setLayout(YLayout);
        YLayout.setHorizontalGroup(
            YLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BodyY, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(HeaderY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        YLayout.setVerticalGroup(
            YLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YLayout.createSequentialGroup()
                .addComponent(HeaderY, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BodyY, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
        );

        mnl_content.add(Y, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        if(cbxD.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "PILIH SALAH SATU TANGGAL TERTERA","WARNING",JOptionPane.WARNING_MESSAGE);
        }else{
            HashMap parameter = new HashMap();
            parameter.put("tgl", cbxD.getSelectedItem().toString());
            try{
                BodyD.removeAll();
                BodyD.repaint();
                BodyD.revalidate();
                String path = "src/reports/rpDays.jrxml";
                JasperReport report = JasperCompileManager.compileReport(path);
                JasperPrint cetak = JasperFillManager.fillReport(report, parameter, koneksi.getRoot());
            
                JRViewer viewer = new JRViewer(cetak);
                viewer.setVisible(true);
                BodyD.add(viewer);
            }catch (JRException e){
                JOptionPane.showMessageDialog(this, "ADA KESALAHAN PADA REPORT","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        if(cbxM.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "PILIH SALAH SATU BULAN TERTERA","WARNING",JOptionPane.WARNING_MESSAGE);
        }else{
            HashMap parameter = new HashMap();
            parameter.put("tgl", cbxM.getSelectedItem().toString());
            try{
                BodyM.removeAll();
                BodyM.repaint();
                BodyM.revalidate();
                String path = "src/reports/rpMonths.jrxml";
                JasperReport report = JasperCompileManager.compileReport(path);
                JasperPrint cetak = JasperFillManager.fillReport(report, parameter, koneksi.getRoot());
            
                JRViewer viewer = new JRViewer(cetak);
                viewer.setVisible(true);
                BodyM.add(viewer);
            }catch (JRException e){
                JOptionPane.showMessageDialog(this, "ADA KESALAHAN PADA REPORT","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnMActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        if(cbxY.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "PILIH SALAH SATU TAHUN TERTERA","WARNING",JOptionPane.WARNING_MESSAGE);
        }else{
            HashMap parameter = new HashMap();
            parameter.put("tgl", cbxY.getSelectedItem().toString());
            try{
                BodyY.removeAll();
                BodyY.repaint();
                BodyY.revalidate();
                String path = "src/reports/rpYears.jrxml";
                JasperReport report = JasperCompileManager.compileReport(path);
                JasperPrint cetak = JasperFillManager.fillReport(report, parameter, koneksi.getRoot());
            
                JRViewer viewer = new JRViewer(cetak);
                viewer.setVisible(true);
                BodyY.add(viewer);
            }catch (JRException e){
                JOptionPane.showMessageDialog(this, "ADA KESALAHAN PADA REPORT","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnYActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyD;
    private javax.swing.JPanel BodyM;
    private javax.swing.JPanel BodyY;
    private javax.swing.JPanel D;
    private javax.swing.JPanel HeaderD;
    private javax.swing.JPanel HeaderM;
    private javax.swing.JPanel HeaderY;
    private javax.swing.JPanel M;
    private javax.swing.JPanel Y;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnY;
    private javax.swing.JComboBox<String> cbxD;
    private javax.swing.JComboBox<String> cbxM;
    private javax.swing.JComboBox<String> cbxY;
    private javax.swing.JLabel lbjdlD;
    private javax.swing.JLabel lbjdlM;
    private javax.swing.JLabel lbjdlY;
    private javax.swing.JLabel lbvarD;
    private javax.swing.JLabel lbvarM;
    private javax.swing.JLabel lbvarY;
    private javax.swing.JPanel mnl_content;
    // End of variables declaration//GEN-END:variables
}
