package panel;

import config.rootdb;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import form.frmenu;

public class pntrans extends javax.swing.JPanel {
    
    private rootdb con = new rootdb();
    private frmenu saveOnly;
    private ResultSet rs;
    private DefaultTableModel dtm;
    private String [] jdlTable ={"Kode Barang","Nama Barang","Harga Per-satuan","Jumlah Per-satuan","Total Harga Per-satuan"};
    private Date sekarang = new Date();
    private SimpleDateFormat sftgl = new SimpleDateFormat("dd/MM/yyyy");
    private DecimalFormat koma = new DecimalFormat("#,##,###");
    private DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    private DecimalFormatSymbols RpIndo = new DecimalFormatSymbols();
    private String byr;    
    private double byr2;
    
    private void autoKd(){
        try{
           SimpleDateFormat ftgl = new SimpleDateFormat("yydd");
           rs=con.adapter.executeQuery("SELECT * FROM nota ORDER BY idtrs DESC");
           if(rs.next()){
               String kdTrs = rs.getString("idtrs").substring(6);
               int noTrs = (Integer.valueOf(kdTrs)+1);
               txtNotrs.setText("T"+ftgl.format(sekarang)+"N"+noTrs);
           }else{
               txtNotrs.setText("T"+ftgl.format(sekarang)+"N"+"0");
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "NOMOR TRANSAKSI GAGAL TAMPIL !!!","WARNING",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void tableTampil(){
        dtm = new DefaultTableModel(null,jdlTable);
        vTabletrs.setModel(dtm);
    }
    
    private void caltbyr(){
        int baris = vTabletrs.getRowCount();
        long jlmh,totbyr = 0;
        for(int i=0;i<baris;i++){
            jlmh = Long.valueOf(vTabletrs.getValueAt(i, 4).toString());
            totbyr = totbyr+jlmh;
        }
        txtTotby.setText(kursIndonesia.format(totbyr));
    }
    
    private void kosong(){
        txtNplg.setText("");
        txtIdbgtrs.setText("");
        txtNbrgtrs.setText("");
        txtSktrs.setText("");
        txtJbltrs.setText("");
        txtTotby.setText("Rp. 0.00");
        txtPyr.setText("");
        txtKbn.setText("Rp. 0.00");
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
    }
    
    public pntrans(String nmusr) {
        con.root();
        initComponents();
        autoKd();
        tableTampil();
        
        RpIndo.setCurrencySymbol("Rp. ");
        RpIndo.setMonetaryDecimalSeparator('.');
        RpIndo.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(RpIndo);
        
        txtTotby.setText("Rp. 0.00");
        txtKbn.setText("Rp. 0.00");
        txtNusr.setText(nmusr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnt_content = new javax.swing.JPanel();
        lb_jdlKrwn = new javax.swing.JLabel();
        lbNusr = new javax.swing.JLabel();
        txtNusr = new javax.swing.JTextField();
        lbNotrs = new javax.swing.JLabel();
        txtNotrs = new javax.swing.JTextField();
        lbNplg = new javax.swing.JLabel();
        txtNplg = new javax.swing.JTextField();
        lbIdbrgtrs = new javax.swing.JLabel();
        txtIdbgtrs = new javax.swing.JTextField();
        lbNbrgtrs = new javax.swing.JLabel();
        txtNbrgtrs = new javax.swing.JTextField();
        lbSktrs = new javax.swing.JLabel();
        txtSktrs = new javax.swing.JTextField();
        lbJbltrs = new javax.swing.JLabel();
        txtJbltrs = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vTabletrs = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false;
            }
        };
        lbTotrs = new javax.swing.JLabel();
        txtTotby = new javax.swing.JTextField();
        lbPyr = new javax.swing.JLabel();
        txtPyr = new javax.swing.JTextField();
        lbKn = new javax.swing.JLabel();
        txtKbn = new javax.swing.JTextField();
        btnBytrs = new javax.swing.JButton();
        btnDeltrs = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        lb_jdlKrwn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb_jdlKrwn.setText("FORM TRANSAKSI");

        lbNusr.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbNusr.setText("Nama Pengguna");

        txtNusr.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtNusr.setEnabled(false);

        lbNotrs.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbNotrs.setText("No. Transaksi");

        txtNotrs.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtNotrs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNotrs.setEnabled(false);

        lbNplg.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbNplg.setText("Nama Pelanggan");

        txtNplg.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        lbIdbrgtrs.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbIdbrgtrs.setText("ID Barang");

        txtIdbgtrs.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtIdbgtrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdbgtrsActionPerformed(evt);
            }
        });
        txtIdbgtrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdbgtrsKeyTyped(evt);
            }
        });

        lbNbrgtrs.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbNbrgtrs.setText("Nama Barang");

        txtNbrgtrs.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtNbrgtrs.setEnabled(false);

        lbSktrs.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbSktrs.setText("Stok Barang");

        txtSktrs.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtSktrs.setEnabled(false);

        lbJbltrs.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbJbltrs.setText("Jumlah Pembelian");

        txtJbltrs.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtJbltrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJbltrsActionPerformed(evt);
            }
        });
        txtJbltrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJbltrsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJbltrsKeyTyped(evt);
            }
        });

        vTabletrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        vTabletrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vTabletrsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(vTabletrs);

        lbTotrs.setFont(new java.awt.Font("Segoe UI Symbol", 1, 28)); // NOI18N
        lbTotrs.setText("TOTAL PEMBAYARAN");

        txtTotby.setEditable(false);
        txtTotby.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtTotby.setEnabled(false);

        lbPyr.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbPyr.setText("PEMBAYARAN");

        txtPyr.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtPyr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPyrKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPyrKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPyrKeyTyped(evt);
            }
        });

        lbKn.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        lbKn.setText("KEMBALIAN");

        txtKbn.setBackground(new java.awt.Color(242, 242, 242));
        txtKbn.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtKbn.setEnabled(false);

        btnBytrs.setBackground(new java.awt.Color(51, 102, 255));
        btnBytrs.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnBytrs.setForeground(new java.awt.Color(255, 255, 255));
        btnBytrs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cart 2.png"))); // NOI18N
        btnBytrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBytrsActionPerformed(evt);
            }
        });

        btnDeltrs.setBackground(new java.awt.Color(51, 102, 255));
        btnDeltrs.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnDeltrs.setForeground(new java.awt.Color(255, 255, 255));
        btnDeltrs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/erase.png"))); // NOI18N
        btnDeltrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeltrsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mnt_contentLayout = new javax.swing.GroupLayout(mnt_content);
        mnt_content.setLayout(mnt_contentLayout);
        mnt_contentLayout.setHorizontalGroup(
            mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnt_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnt_contentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbTotrs)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotby, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnt_contentLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeltrs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mnt_contentLayout.createSequentialGroup()
                        .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdbgtrs, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIdbrgtrs))
                        .addGap(18, 18, 18)
                        .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mnt_contentLayout.createSequentialGroup()
                                .addComponent(lbNbrgtrs)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNbrgtrs))
                        .addGap(18, 18, 18)
                        .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnt_contentLayout.createSequentialGroup()
                                .addComponent(lbSktrs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbJbltrs))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnt_contentLayout.createSequentialGroup()
                                .addComponent(txtSktrs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtJbltrs, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnt_contentLayout.createSequentialGroup()
                        .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mnt_contentLayout.createSequentialGroup()
                                .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNusr)
                                    .addComponent(lbNotrs)
                                    .addComponent(lbNplg))
                                .addGap(30, 30, 30)
                                .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNusr, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNotrs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNplg))
                                .addGap(21, 21, 21)
                                .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mnt_contentLayout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(lbPyr))
                                    .addComponent(txtPyr, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mnt_contentLayout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(lbKn))
                                    .addComponent(txtKbn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mnt_contentLayout.createSequentialGroup()
                                .addComponent(lb_jdlKrwn)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnBytrs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mnt_contentLayout.setVerticalGroup(
            mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mnt_contentLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lb_jdlKrwn)
                .addGap(6, 6, 6)
                .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mnt_contentLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNusr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNusr))
                        .addGap(20, 20, 20)
                        .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNotrs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNotrs))
                        .addGap(20, 20, 20)
                        .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNplg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNplg)))
                    .addGroup(mnt_contentLayout.createSequentialGroup()
                        .addComponent(lbPyr)
                        .addGap(10, 10, 10)
                        .addComponent(txtPyr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbKn)
                        .addGap(10, 10, 10)
                        .addComponent(txtKbn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBytrs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNbrgtrs)
                        .addComponent(lbIdbrgtrs))
                    .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbSktrs)
                        .addComponent(lbJbltrs)))
                .addGap(18, 18, 18)
                .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdbgtrs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNbrgtrs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtJbltrs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSktrs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeltrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mnt_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mnt_contentLayout.createSequentialGroup()
                        .addComponent(lbTotrs)
                        .addGap(9, 9, 9))
                    .addComponent(txtTotby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(mnt_content, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdbgtrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdbgtrsActionPerformed
        try{
            rs=con.adapter.executeQuery("SELECT * FROM data WHERE kdbrg = '"+txtIdbgtrs.getText()+"'");
            if(rs.next()){
                txtNbrgtrs.setText(rs.getString(4));
                txtSktrs.setText(rs.getString(6));
                txtJbltrs.requestFocus();
            }else{
                JOptionPane.showMessageDialog(null,"ID BARANG TIDAK DITEMUKAN !!!","WARNING",JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"DATABASE TIDAK TERKONEKSI !!!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtIdbgtrsActionPerformed

    private void txtIdbgtrsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdbgtrsKeyTyped
        if(txtIdbgtrs.getText().equals("")){
            txtNbrgtrs.setText("");
            txtSktrs.setText("");
        }
    }//GEN-LAST:event_txtIdbgtrsKeyTyped

    private void txtJbltrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJbltrsActionPerformed
        try{
            rs=con.adapter.executeQuery("SELECT * FROM data WHERE kdbrg = '"+txtIdbgtrs.getText()+"'");
            if(rs.next()){
                int jmlh = Integer.valueOf(txtJbltrs.getText());
                Object [] rows = {rs.getString(2),rs.getString(4),rs.getString(5),txtJbltrs.getText(),(Long.valueOf(rs.getInt(5))*jmlh)};
                dtm.addRow(rows);
                vTabletrs.setModel(dtm);
            }
            txtIdbgtrs.setText("");
            txtNbrgtrs.setText("");
            txtSktrs.setText("");
            txtJbltrs.setText("");
            txtIdbgtrs.requestFocus();
            caltbyr();
        }catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtJbltrsActionPerformed

    private void btnBytrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBytrsActionPerformed
        if(txtNusr.getText().equals("")||txtNplg.getText().equals("")||txtPyr.getText().equals("")||txtTotby.getText().equals("Rp. 0.00")||vTabletrs.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"TRANSAKSI MASIH KOSONG !!!","WARNING",JOptionPane.WARNING_MESSAGE);  
        }else{
            int bayar = Integer.valueOf(txtPyr.getText().replace("Rp. ", "").replace(",", ""));
            int tbayar = Integer.valueOf(txtTotby.getText().replace("Rp. ", "").replace(",", "").replace(".00", ""));
            int kbayar = Integer.valueOf(txtKbn.getText().replace("Rp. ", "").replace(",","").replace(".00",""));
            if(bayar<tbayar){
                JOptionPane.showMessageDialog(null,"UANG TIDAK CUKUP !!!","WARNING",JOptionPane.WARNING_MESSAGE);
            }else{
                try{
                    con.adapter.executeUpdate("INSERT INTO nota VALUES('"+txtNotrs.getText()+"','"+txtNusr.getText()+"','"+txtNplg.getText()+"',"
                                                                    + "'"+sftgl.format(sekarang)+"','"+tbayar+"','"+bayar+"','"+kbayar+"')");
                    for(int i=0;i<vTabletrs.getRowCount();i++){
                        con.adapter.executeUpdate("INSERT INTO transaction VALUES('"+txtNotrs.getText()+"','"+vTabletrs.getValueAt(i, 0)+"',"
                                                                               + "'"+vTabletrs.getValueAt(i, 1)+"','"+vTabletrs.getValueAt(i, 2)+"','"+vTabletrs.getValueAt(i, 3)+"',"
                                                                               + "'"+vTabletrs.getValueAt(i, 4)+"')");
                    }
                    JOptionPane.showMessageDialog(null,"TRANSAKSI BERHASIL !!!","INFO",JOptionPane.INFORMATION_MESSAGE);
                    kosong();
                    autoKd();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"TRANSAKSI GAGAL !!!","ERROR",JOptionPane.ERROR_MESSAGE);
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_btnBytrsActionPerformed

    private void txtPyrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPyrKeyTyped
        char typed = evt.getKeyChar();
        int cek = txtPyr.getText().length();
        if(cek>=0 && cek<=20){
            if(!Character.isDigit(typed)){
                evt.consume();
            }
        }else if (cek>=20){
            if(Character.isDigit(typed) || !Character.isDigit(typed)){
                evt.consume();
            }
        }
        
        if(cek==0){
            txtPyr.setText("Rp. ");
        }else if(cek==3){
            txtPyr.setText("");
        }
    }//GEN-LAST:event_txtPyrKeyTyped

    private void txtPyrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPyrKeyReleased
        try{
            byr = String.valueOf(txtPyr.getText().substring(4));
            byr2 = Double.parseDouble(byr.replaceAll("\\,", ""));
            txtPyr.setText("Rp. "+ koma.format(byr2));
            
            long byr = Long.valueOf(txtPyr.getText().replace("Rp. ", "").replace(",", ""));
            long tbyr = Long.valueOf(txtTotby.getText().replace("Rp. ", "").replace(",", "").replace(".00", ""));
            long cal = byr-tbyr;
            txtKbn.setText("Rp. " + koma.format(cal) +".00");
        }catch (Exception e){
            txtKbn.setText("Rp. 0.00");
        }
    }//GEN-LAST:event_txtPyrKeyReleased

    private void txtPyrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPyrKeyPressed
        if(evt.getKeyCode()==8){
            if(txtPyr.getText().length()==0){
                txtPyr.setText("    ");
            }
        }
    }//GEN-LAST:event_txtPyrKeyPressed

    private void btnDeltrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeltrsActionPerformed
        kosong();
    }//GEN-LAST:event_btnDeltrsActionPerformed

    private void txtJbltrsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJbltrsKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtJbltrsKeyTyped

    private void vTabletrsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vTabletrsKeyPressed
        int typed = evt.getKeyCode();
        if(typed==127){
            int row = vTabletrs.getSelectedRow();
            if(vTabletrs.getSelectedRowCount()==1){
                vTabletrs.getSelectionModel().addSelectionInterval(row, row-1);
                dtm.removeRow(row);
                vTabletrs.requestFocus();
            }else{
                evt.consume();
            }
        }
    }//GEN-LAST:event_vTabletrsKeyPressed

    private void txtJbltrsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJbltrsKeyPressed
        if(evt.getKeyCode()==8){
            if(txtJbltrs.getText().equals("")){
                txtIdbgtrs.requestFocus();
            }
        }
    }//GEN-LAST:event_txtJbltrsKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBytrs;
    private javax.swing.JButton btnDeltrs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIdbrgtrs;
    private javax.swing.JLabel lbJbltrs;
    private javax.swing.JLabel lbKn;
    private javax.swing.JLabel lbNbrgtrs;
    private javax.swing.JLabel lbNotrs;
    private javax.swing.JLabel lbNplg;
    private javax.swing.JLabel lbNusr;
    private javax.swing.JLabel lbPyr;
    private javax.swing.JLabel lbSktrs;
    private javax.swing.JLabel lbTotrs;
    private javax.swing.JLabel lb_jdlKrwn;
    private javax.swing.JPanel mnt_content;
    private javax.swing.JTextField txtIdbgtrs;
    private javax.swing.JTextField txtJbltrs;
    private javax.swing.JTextField txtKbn;
    private javax.swing.JTextField txtNbrgtrs;
    private javax.swing.JTextField txtNotrs;
    private javax.swing.JTextField txtNplg;
    private javax.swing.JTextField txtNusr;
    private javax.swing.JTextField txtPyr;
    private javax.swing.JTextField txtSktrs;
    private javax.swing.JTextField txtTotby;
    private javax.swing.JTable vTabletrs;
    // End of variables declaration//GEN-END:variables
}
